config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :users
  resources :contents

  resources :contents do
    member do
      put "like", to: "contents#like"
      put "dislike", to: "contents#dislike"
      put "mark", to: "contents#mark_content"
      put "unmark", to: "contents#unmark"
    end
  end

  resources :playlist_items do
    collection { post :sort }
  end

   root 'contents#index'
   get '/calendar' => 'pages#calendar'
   get '/readlater' => 'pages#readlater'
   get '/popular' => 'contents#popular'
   get 'tagged' => 'contents#tagged', :as => 'tagged'
   get '/info' => 'pages#info'

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_many :marked_contents
  has_many :marked_by,  class_name: 'User', through: :marked_contents, source: :user

  has_many :playlist_items
  has_many :playlists, through: :playlist_items

  acts_as_taggable_on :tags
  acts_as_votable

  validates :category_id, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true

  mount_uploader :image, ImageUploader

  nilify_blanks :only => [:video]

  def self.search(query)
    where("title LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
  end

  def self.most_popular
    self.order("cached_votes_score DESC")
  end

  def tv_img_url
    image.url(:tv)
  end

  def img_url
    image.url()
  end

  def iphone_url
    image.url(:iphone)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index, :tagged, :popular]

  # GET /contents
  # GET /contents.json
  def index

    if params[:search]
      @contents = Content.search(params[:search])
    else
      @contents = Content.all.order('created_at DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @contents, :only => [:id, :title, :description, :category_id, :video, :event_datetime,
      #                                                :event_site, :limit_date, :image, :user_id, :created_at] }
      format.json { render json: @contents, :only => [:id, :title, :description, :category_id, :video, :event_datetime,
                                                      :event_site, :limit_date], :methods => [:tv_img_url, :img_url, :iphone_url] }
    end
  end

  def get_events
    @contents = Content.find_by_category_id(1)
  end

  helper_method :get_events

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  def get_category(category_id)
    @name = Category.find(category_id).name
  end

  helper_method :get_category

  def get_author(id)
    @name = User.find(id).name
  end

  helper_method :get_author

  def like
    @content = Content.find(params[:id])
    @content.liked_by current_user

    if request.xhr?
      render json: { count: @content.get_likes.size, id: params[:id] }
    else
      redirect_to @content
    end
  end

  def dislike
    @content = Content.find(params[:id])
    @content.disliked_by current_user

    if request.xhr?
      render json: { count: @content.get_likes.size, id: params[:id] }
    else
      redirect_to @content
    end
  end

  def popular
    @contents = Content.order('cached_votes_up DESC').limit(5)
  end

  helper_method :popular

  def tagged
    if params[:tag].present?
      @contents = Content.tagged_with(params[:tag])
    else
      @contents = Content.all
    end
  end

  def mark_content
    @user = User.find(current_user.id)
    @content = Content.find(params[:id])
    begin
      @user.read_later(@content)
    rescue
    end
    redirect_to readlater_path
  end

  def unmark
      @user = User.find(current_user.id)
      @content = Content.find(params[:id])
      @user.markings.destroy (@content)
      redirect_to readlater_path
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.description = BlueCloth.new(@content.description).to_html
    @content.user_id = current_user

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :description, :category_id, :video, :limit_date, :event_site, :event_datetime, :tag_list, :image)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h4>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <script>

      $(document).ready(function()
      {
          $("#limit_date").hide();

          if($("#content_category_id").val() == 1)
          {
              $("#limit_date").hide();
              $("#event_date").show();
              $("#event_site").show();
          }
          else if($("#content_category_id").val() == 2 || $("#content_category_id").val() == 3)
          {
              $("#limit_date").hide();
              $("#event_date").hide();
              $("#event_site").hide();
          }
          else if($("#content_category_id").val() == 4)
          {
              $("#limit_date").show();
              $("#event_date").hide();
              $("#event_site").hide();
          }
          else if($("#content_category_id").val() == 5)
          {
              $("#limit_date").hide();
              $("#event_date").hide();
              $("#event_site").hide();
          }

              $("#content_category_id").change(
                function()
                {
                    if($("#content_category_id").val() == 1)
                    {
                        $("#limit_date").hide();
                        $("#event_date").show();
                        $("#event_site").show();
                    }
                    else if($("#content_category_id").val() == 2 || $("#content_category_id").val() == 3)
                    {
                        $("#limit_date").hide();
                        $("#event_date").hide();
                        $("#event_site").hide();
                    }
                    else if($("#content_category_id").val() == 4)
                    {
                        $("#limit_date").show();
                        $("#event_date").hide();
                        $("#event_site").hide();
                    }
                    else if($("#content_category_id").val() == 5)
                    {
                        $("#limit_date").hide();
                        $("#event_date").hide();
                        $("#event_site").hide();
                    }
                }
              )

          $(function() {
              $('.input-row').select2({tags:["fct/unl", "campustv", "informatica"], tokenSeparators: [",", " "]})
          });
      });

  </script>

  <div class="field" id="category">
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>

  <div class="field" id="title">
    <br>
    <%= f.text_field :title, :placeholder => "Título", :class => "form-control" %>
  </div>

  <div class="field" id="description">
    <br>
    <%= f.text_area :description, 'data-provide'=>'markdown', :rows => "10", :placeholder => "Texto" %>
  </div>

  <div class="field" id="video">
    <br>
    <%= f.text_field :video, placeholder: "Video URL (YouTube)", :class => "form-control" %>
  </div>

  <div class="field" id="limit_date">
    <br>
    <strong>Data Limite: </strong>
    <%= f.text_field :limit_date %>
  </div>

    <div class="field" id="event_date">
      <br>
      <strong>Data: </strong>
      <%= f.datetime_select :event_datetime, :include_blank => true %>
    </div>

  <div class="field" id="event_site">
    <br>
    <%= f.text_field :event_site, :placeholder => "Local do evento", :class => "form-control" %>
  </div>

  <div class="field">
    <br>
    <strong>Imagem: </strong>
    <%= f.file_field :image %>
  </div>

  <div class="field" id="tags">
  <br>
    <%= f.text_field :tag_list, :class => "form-control input-row", :placeholder => "Tags" %>
  </div>

  <div class="actions">
    <br>
    <%= f.submit "Submeter", :class => "btn btn-default" %>
  </div>

<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<script>
    $(document).ready(function() {
        $("#content_category_id").hide();
    })
</script>

app/views/contents/index.html.erb
<div id="news">
  <% @contents.each do |content| %>
      <div class="content-container">
        <div class="content-title">
          <h4 title="<%= content.title %>"><%= link_to truncate(content.title, length: 70, omission: '... '), content %></h4>
        </div>
        <div class="content-image">
          <% if content.image.url(:thumb) == nil %>
              <% if content.category_id == 1 %>
                <%= image_tag('calendar.png') %>
              <% elsif content.category_id == 2 %>
                  <%= image_tag('news.png') %>
              <% elsif content.category_id == 3 %>
                  <%= image_tag('pedagogical.png') %>
              <% elsif content.category_id == 4 %>
                  <%= image_tag('work.png') %>
              <% elsif content.category_id == 5 %>
                  <%= image_tag('reports.png') %>
              <% end %>
          <% else %>
              <%= image_tag(content.image.url(:thumb)) %>
          <% end %>
        </div>
        <div class="content-text">
          <div class="content-type">
            <span><a href="<%= category_path(content.category_id) %>"><%= get_category(content.category_id) %></a></span>
            <span> · </span>
            <span id="pub_date"><%= time_ago_in_words(content.created_at) %></span>
            <% if not(content.video.blank?) %>
                <span> · </span>
                <span><i class="glyphicon glyphicon-facetime-video"></i></span>
            <% end %>

            <span> · </span>

            <% if user_signed_in? %>
                <% if current_user.liked? content %>
                    <%= link_to raw('<i class="glyphicon glyphicon-star"></i>'), dislike_content_path(content), remote: true,class: 'vote', method: :put, data: { toggle_text: '<i class="glyphicon glyphicon-star-empty"></i>', toggle_href: like_content_path(content), id: content.id } %>
                <% else %>
                    <%= link_to raw('<i class="glyphicon glyphicon-star-empty"></i>'), like_content_path(content), remote: true, class: 'vote', method: :put, data: { toggle_text: '<i class="glyphicon glyphicon-star"></i>', toggle_href: dislike_content_path(content), id: content.id } %>
                <% end %>
            <% else %>
                <i class="glyphicon glyphicon-star"></i>
            <% end %>

            <span class="votes-count" data-id="<%= content.id %>">
                    <%= content.get_likes.size %>
            </span>

          </div>
          <div class="content-description">
            <p>
              <%= truncate_html(content.description.html_safe, length: 300, omission: '... ') %>
            </p>
          </div>
        </div>
      </div>
<% end %>

</div>

app/views/contents/new.html.erb
<h1>Adicionar conteúdo</h1>
<hr>

<div class="alert alert-info alert-dismissable">
  <span class="close" data-dismiss="alert">×</span>
  <span><strong>Atenção!</strong> Não se esqueça de atribuir uma categoria à sua publicação.</span>
</div>

<%= render 'form' %>
<br>
<%= link_to 'Voltar', contents_path %>

app/views/contents/popular.html.erb
<p class="lead">Mais populares</p>
<hr>

<% popular.each do |c| %>
        <h5 class="popular_title"><%= link_to c.title, c %>
          <span class="likes_number"><i class="glyphicon glyphicon-star"></i> <%= c.get_likes.size %></span></h5>
        <hr>
<% end %>

app/views/contents/show.html.erb
<div id="article">
  <h3><%= @content.title %></h3>

  <div id="article_metadata">
    <span id="author"><%= link_to get_author(@content.user_id), user_path(@content.user_id) %></span><span> · </span>
    <span id="pub_date"><%= @content.created_at %></span>
    <span> · </span><%= link_to get_category(@content.category_id), category_path(@content.category_id) %>

  </div>

  <hr>

  <div id="article_content">
    <%= image_tag(@content.image) %>
    <%= @content.description.html_safe %>
  </div>

  <% unless @content.video.blank? %>
        <iframe width="420" height="345" src="<%= @content.video %>">
        </iframe>
  <% end %>

  <% unless @content.event_datetime.blank? %>
      <h5>Data: <%= @content.event_datetime %></h5>
  <% end %>
  <% unless @content.event_site.blank? %>
      <h5>Local: <%= @content.event_site %></h5>
  <% end %>
  <% unless @content.limit_date.blank? %>
      <h5>Data limite: <%= @content.limit_date %></h5>
  <% end %>

  <hr>

  <% if user_signed_in? %>
      <% if current_user.liked? @content %>
          <%= link_to raw('<i class="glyphicon glyphicon-star"></i>'), dislike_content_path(@content), remote: true, class: 'vote', method: :put, data: { toggle_text: '<i class="glyphicon glyphicon-star-empty"></i>', toggle_href: like_content_path(@content), id: @content.id } %>
      <% else %>
          <%= link_to raw('<i class="glyphicon glyphicon-star-empty"></i>'), like_content_path(@content), remote: true, class: 'vote', method: :put, data: { toggle_text: '<i class="glyphicon glyphicon-star"></i>', toggle_href: dislike_content_path(@content), id: @content.id } %>
      <% end %>
  <% else %>
      <i class="glyphicon glyphicon-star"></i>
  <% end %>

  <span class="votes-count" data-id="<%= @content.id %>">
    <%= @content.get_likes.size %>
  </span>
  <span> · </span>

  Tags:
  <% @content.tags.any? %>
      <% @content.tags.each do |tag| %>
      <%= link_to tag.name, tagged_url(:tag => tag.name) %>
  <% end %>
</div>

<% unless(current_user.presence_in(@content.marked_by)) %>
    <%= link_to "Ler mais tarde", mark_content_path(@content), method: :put %>
<% end %>

app/views/contents/tagged.html.erb
<div id="news">
  <p class="lead">Resultados para a tag: <%= params[:tag] %></p>
  <hr>
  <% @contents.each do |content| %>
      <div class="content-container">
        <div class="content-title">
          <h4 title="<%= content.title %>"><%= link_to truncate(content.title, length: 70, omission: '... '), content %></h4>
        </div>
        <div class="content-image">
          <% if content.image.url(:thumb) == nil %>
              <% if content.category_id == 1 %>
                  <%= image_tag('calendar.png') %>
              <% elsif content.category_id == 2 %>
                  <%= image_tag('news.png') %>
              <% elsif content.category_id == 3 %>
                  <%= image_tag('pedagogical.png') %>
              <% elsif content.category_id == 4 %>
                  <%= image_tag('work.png') %>
              <% elsif content.category_id == 5 %>
                  <%= image_tag('reports.png') %>
              <% end %>
          <% else %>
              <%= image_tag(content.image.url(:thumb)) %>
          <% end %>
        </div>
        <div class="content-text">
          <div class="content-type">
            <span><a href="<%= category_path(content.category_id) %>"><%= get_category(content.category_id) %></a></span>
            <span> · </span>
            <span id="pub_date"><%= time_ago_in_words(content.created_at) %></span>
          </div>
          <div class="content-description">
            <p>
              <%= truncate_html(content.description.html_safe, length: 300, omission: '... ') %>
            </p>
          </div>
        </div>
      </div>
  <% end %>
</div>