config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :users
  resources :contents

  resources :contents do
    member do
      put "like", to: "contents#like"
      put "dislike", to: "contents#dislike"
      put "mark", to: "contents#mark_content"
      put "unmark", to: "contents#unmark"
    end
  end

  resources :playlist_items do
    collection { post :sort }
  end

   root 'contents#index'
   get '/calendar' => 'pages#calendar'
   get '/readlater' => 'pages#readlater'
   get '/popular' => 'contents#popular'
   get 'tagged' => 'contents#tagged', :as => 'tagged'
   get '/info' => 'pages#info'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter

  has_many :contents
  has_many :marked_contents
  has_many :markings, class_name: 'Content', through: :marked_contents, source: :content

  def read_later(content)
    markings << content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def user_total_likes()
    @user = User.find(params[:id])
    @total = 0

    @user.contents.each do |c|
      @total = @total + c.get_likes.size
    end

    return @total
  end

  helper_method :user_total_likes

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<hr>

<p>
  <strong>Função: </strong>
  <% if @user.is_teacher %>
      <%= "Professor" %>
  <% else %>
      <%= "Aluno" %>
  <% end %>
</p>

<p>
  <strong>Popularidade: </strong>
  <%= user_total_likes %> <i class="glyphicon glyphicon-star"></i>
</p>

<p>
  <strong>Nº de favoritos: </strong>
  <%= @user.find_liked_items.size %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<br>
<h3>Conteúdos inseridos</h3>
<hr>

<% if @user.contents.length > 0 %>
    <% @user.contents.order('created_at DESC').each do |content| %>

        <h5 class="user_content"><%= link_to content.title, "#" + content.id.to_s + "modal", data: {toggle: "modal"} %>
          <span class="likes_number"> · <%= content.get_likes.size %> <i class="glyphicon glyphicon-star"></i></span>
        </h5>
        <hr>

        <!-- Modal -->
        <div class="modal fade" id="<%= content.id.to_s %>modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><%= content.title %></h4>
              </div>
              <div class="modal-body">

                <% if not(current_user.blank?) %>
                    <% if content.presence_in(User.find(current_user).contents) %>
                        <div class="row">
                          <div class="col-md-4"><i class="glyphicon glyphicon-eye-open"></i></div>
                          <div class="col-md-4"><i class="glyphicon glyphicon-edit"></i></div>
                          <div class="col-md-4"><i class="glyphicon glyphicon-trash"></i></div>
                        </div>

                        <div class="row">
                          <div class="col-md-4"><%= link_to 'Ver', content_path(content) %></div>
                          <div class="col-md-4"><%= link_to 'Editar', edit_content_path(content) %></div>
                          <div class="col-md-4"><%= link_to 'Apagar', content, method: :delete, data: { confirm: 'Tem a certeza?' } %></div>
                        </div>
                    <% else %>
                        <div class="row">
                          <div class="col-md-6"><i class="glyphicon glyphicon-eye-open"></i></div>
                          <div class="col-md-6"><i class="glyphicon glyphicon-warning-sign"></i></div>
                        </div>

                        <div class="row">
                          <div class="col-md-6"><%= link_to 'Ver', content_path(content) %></div>
                          <div class="col-md-6"><%= link_to 'Reportar publicação' %></div>
                        </div>
                    <% end %>
                <% else %>
                    <div class="row">
                      <div class="col-md-12"><i class="glyphicon glyphicon-eye-open"></i></div>
                    </div>
                    <div class="row">
                      <div class="col-md-12"><%= link_to 'Ver', content_path(content) %></div>
                    </div>
                <% end %>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% else %>
    <div class="alert alert-warning">
      Este utilizador não publicou qualquer conteúdo!
    </div>
<% end %>

<h3>Favoritos</h3>
<hr>

<% if @user.find_liked_items.length > 0 %>
    <% @user.find_liked_items.each do |c| %>

        <h5 class="user_content"><%= link_to c.title, c %>
          <span class="likes_number"> · <%= c.get_likes.size %> <i class="glyphicon glyphicon-star"></i></span>
        </h5>
        <hr>
    <% end %>
<% else %>
    <div class="alert alert-warning">
      Este utilizador ainda não tem favoritos!
    </div>
<% end %>