config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :users
  resources :contents

  resources :contents do
    member do
      put "like", to: "contents#like"
      put "dislike", to: "contents#dislike"
      put "mark", to: "contents#mark_content"
      put "unmark", to: "contents#unmark"
    end
  end

  resources :playlist_items do
    collection { post :sort }
  end

   root 'contents#index'
   get '/calendar' => 'pages#calendar'
   get '/readlater' => 'pages#readlater'
   get '/popular' => 'contents#popular'
   get 'tagged' => 'contents#tagged', :as => 'tagged'
   get '/info' => 'pages#info'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FCT TV</title>
  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'general' %>
  <%= stylesheet_link_tag 'header' %>
  <%= stylesheet_link_tag 'nav-bar' %>

  <%= yield :css %>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="header">
    <div id="logo"><%= image_tag ("Logo.png") %></div>
    <div id="logout">
      <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, :method => :delete, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-log-out"></i>
          <% end %>
      <% else %>
          <%= link_to new_user_session_path, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-log-in"></i>
          <% end %>
      <% end %>
    </div>
    <div id="menuButton" class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-cog"></span>
      </button>
      <ul class="dropdown-menu right" role="menu">
        <% if user_signed_in? %><li><%= link_to 'Meus conteúdos', user_path(User.find(current_user)) %></li><% end %>
        <li><%= link_to 'Sobre nós', info_path %></li>
        <li class="divider"></li>
        <li><a href="mailto:admin@campustv.pt?subject=Suporte FCT TV">Suporte</a></li>
      </ul>
    </div>
    <% if user_signed_in? %>
        <div id="menuButton" class="btn-group">
          <%= link_to user_path(User.find(current_user)), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-user"></i> <%= current_user.name %>
          <% end %>
        </div>
    <% end %>
    <div id="menuButton" class="btn-group">
      <%= link_to root_path, class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-home"></i>
      <% end %>
    </div>
    <div id="search_box">
      <%= form_tag(contents_path, :method => "get", id: "lol") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Pesquisa", class: 'form-control', type: 'text' %>
      <% end %>
    </div>
    <div id="upload">
      <%= link_to new_content_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
    </div>
  </div>

  <div id="nav-bar">
    <ul id="menu">
      <li><%= link_to('Mais populares', popular_path) %></li>
      <% if current_user %>
        <% if User.find(current_user).name == "Administrador" %><li><%= link_to('Lista de reprodução', playlist_items_path) %></li><% end %>
      <% end %>
      <% if current_user %><li><%= link_to 'Ler mais tarde', readlater_path %></li><% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias</a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="<%= category_path(Category.find_by_name("Eventos")) %>">Eventos</a></li>
          <li><a href="<%= category_path(Category.find_by_name("Notícias FCT")) %>">Notícias FCT</a></li>
          <li><a href="<%= category_path(Category.find_by_name("Avisos Pedagógicos")) %>">Avisos Pedagógicos</a></li>
          <li><a href="<%= category_path(Category.find_by_name("Investigação e Trabalho")) %>">Investigação e Trabalho</a></li>
          <li><a href="<%= category_path(Category.find_by_name("Diversos")) %>">Diversos</a></li>
        </ul>
      </li>
      <li><%= link_to('Agenda', calendar_path) %></li>
      <li><%= link_to 'Ementa', "#ementaModal", data: {toggle: "modal"} %></li>
    </ul>
  </div>

  <div id="content-box">
    <%= yield %>
  </div>

  <div id="footer">
    <span>© Grupo 10 - Projecto Integrador 13/14</span>
    <ul id="footer_menu">
      <li><a href="http://alojamento.fct.unl.pt/">Alojamento</a></li>
      <li><a href="http://emprego.fct.unl.pt/">Emprego</a></li>
      <li><a href="http://www.fct.unl.pt/faq">FAQ</a></li>
      <li><a href=" http://www.fct.unl.pt/">FCT-UNL</a></li>
    </ul>
  </div>

  <div class="modal fade" id="ementaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Ementa</h4>
        </div>
        <div class="modal-body">
          <div id="ementa">
              <p><strong>Sopa:</strong> Canja c/ Massinhas</p>
              <p><strong>Prato Principal:</strong> Frango Assado C/ Arroz - 1079.5 Kcal ; Feijoada Vegetariana-483,3 Kcal</p>
              <p><strong>Dieta:</strong> Lombinhos de Peix/ C/ Molh/ Bran/- 711,32 Kcal</p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>

</div>

</body>
</html>